version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  expense-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expense_db
      SPRING_DATASOURCE_USERNAME: expense_user
      SPRING_DATASOURCE_PASSWORD: expense_pass
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/expense_db
      SPRING_FLYWAY_USER: expense_user
      SPRING_FLYWAY_PASSWORD: expense_pass

volumes:
  postgres_data: